sudo: required #is required to use docker service in travis

language: go

services:
  - docker # required, but travis uses older version of docker :(

install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
  - make docker-build VERSION=0.0.${TRAVIS_BUILD_NUMBER}

before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin

deploy:
- provider: script
  script:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/push-docker.sh; fi'
  skip_cleanup: true
  on:
    branch: main
